preserve_hierarchy: true

files:
  - source: /source/handbooks/*.md
    translation: /locale/%two_letters_code%/handbooks/%original_file_name%
    update_option: update_as_unapproved

  - source: /source/policies/*.md
    translation: /locale/%two_letters_code%/policies/%original_file_name%
    update_option: update_as_unapproved
  - source: /source/policies/coc/*.md
    translation: /locale/%two_letters_code%/policies/coc/%original_file_name%
    update_option: update_as_unapproved

  - source: /source/resources/*.md
    translation: /locale/%two_letters_code%/resources/%original_file_name%
    update_option: update_as_unapproved
  - source: /source/resources/communications/*.md
    translation: /locale/%two_letters_code%/resources/communications/%original_file_name%
    update_option: update_as_unapproved
  - source: /source/resources/curriculum/*.md
    translation: /locale/%two_letters_code%/resources/curriculum/%original_file_name%
    update_option: update_as_unapproved
  - source: /source/resources/general/*.md
    translation: /locale/%two_letters_code%/resources/general/%original_file_name%
    update_option: update_as_unapproved
  - source: /source/resources/instructor-training/*.md
    translation: /locale/%two_letters_code%/resources/instructor-training/%original_file_name%
    update_option: update_as_unapproved
  - source: /source/resources/workshops/*.md
    translation: /locale/%two_letters_code%/resources/workshops/%original_file_name%
    update_option: update_as_unapproved

  - source: /CODE_OF_CONDUCT.md
    translation: /locale/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /CONTRIBUTING.md
    translation: /locale/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /LICENSE.md
    translation: /locale/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /README.md
    translation: /locale/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
